In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Activation, Dropout
from tensorflow.keras.layers import Conv1D, MaxPooling1D, GlobalMaxPooling1D
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split


In [2]:
df = pd.read_csv('D:\Deep Learning\dataset_tingkat_kebahagiaan.csv')
df.head()

sentimen                                              Tweet
0         1  providername pakai providername paket productn...
1         1  providername providername kangen nih kiriman p...
2         1  alhamdulillah setia providername menari tabuha...
3         1                      asik kencang providername url
4         1                      mantap g lte providername url

In [4]:
text = df["Tweet"].tolist()
print(len(text))

2268


In [7]:
y = df["sentimen"]
y = to_categorical(y)
print(y)

[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]


In [9]:
df["sentimen"].value_counts()

0    1134
1    1134
Name: sentimen, dtype: int64

In [10]:
token = Tokenizer()
token.fit_on_texts(text)

In [11]:
token.index_word

{1: 'enak',
 2: 'tempat',
 3: 'makanan',
 4: 'makan',
 5: 'harga',
 6: 'menu',
 7: 'bandung',
 8: 'cukup',
 9: 'nyaman',
 10: 'rasanya',
 11: 'suka',
 12: 'rasa',
 13: 'restoran',
 14: 'pelayanan',
 15: 'kecewa',
 16: 'suasana',
 17: 'malam',
 18: 'bagus',
 19: 'goreng',
 20: 'marah',
 21: 'jalan',
 22: 'mahal',
 23: 'satu',
 24: 'salah',
 25: 'sih',
 26: 'nasi',
 27: 'bikin',
 28: 'keluarga',
 29: 'pemandangan',
 30: 'pas',
 31: 'datang',
 32: 'ayam',
 33: 'steak',
 34: 'indosat',
 35: 'hari',
 36: 'lumayan',
 37: 'pilihan',
 38: 'pesan',
 39: 'kurang',
 40: 'porsi',
 41: 'mantap',
 42: 'baik',
 43: 'tahu',
 44: 'anak',
 45: 'cocok',
 46: 'film',
 47: 'kota',
 48: 'kali',
 49: 'lokasi',
 50: 'kafe',
 51: 'ramah',
 52: 'baru',
 53: 'minuman',
 54: 'pakai',
 55: 'waktu',
 56: 'resto',
 57: 'melihat',
 58: 'bosan',
 59: 'besar',
 60: 'indonesia',
 61: 'teman',
 62: 'providername',
 63: 'memesan',
 64: 'jam',
 65: 'khas',
 66: 'pelayan',
 67: 'mi',
 68: 'daging',
 69: 'membuat',
 70: 'bak

In [22]:
vocab = len(token.index_word)+1
vocab

7848

In [23]:
encode_text = token.texts_to_sequences(text)
print(encode_text)

[[62, 54, 62, 198, 1115, 3380, 3381, 198, 1115, 3382, 539, 109, 62], [62, 62, 339, 115, 2216, 1648, 3383, 62, 82, 100, 1648], [682, 385, 62, 3384, 3385, 3386, 494, 3387, 3388], [131, 757, 62, 758], [41, 579, 1649, 62, 758], [3389, 54, 62, 629, 1650, 385, 62, 22, 759, 2217], [62, 41, 3390, 62], [760, 495, 3391, 1651, 41, 62, 3392, 2218, 758], [41, 62, 1652, 3393], [131, 757, 62], [386, 761, 62, 2219, 3394, 47, 3395, 758], [2220, 85, 385, 3396, 3397, 18, 62, 62, 758], [207, 62, 496, 1653, 3398, 141, 1116, 41], [41, 62, 222, 580, 153, 969, 198, 1324, 1117, 3399, 62, 118, 2221, 62, 3400], [198, 1324, 1654, 970, 62, 8, 293, 2221, 62, 62], [172, 103, 62, 62], [62, 173, 539, 3401, 386, 86], [166, 540, 1655, 539, 541, 387, 62, 385, 62], [166, 540, 1655, 539, 541, 54, 62, 385, 62], [172, 103, 2222, 62, 2216, 460, 62, 3402, 497], [227, 54, 62, 3403, 3404, 2223], [385, 3405, 62], [86, 3406, 207, 579, 62], [207, 62, 388], [3407, 62, 3408, 3409, 3410, 109], [682, 385, 62, 353], [207, 579, 1118, 115

In [24]:
max_kata = 100
X = pad_sequences(encode_text, maxlen = max_kata, padding="post")
X

array([[  62,   54,   62, ...,    0,    0,    0],
       [  62,   62,  339, ...,    0,    0,    0],
       [ 682,  385,   62, ...,    0,    0,    0],
       ...,
       [ 234, 1284,    0, ...,    0,    0,    0],
       [ 310,   15, 1652, ...,    0,    0,    0],
       [ 126,  126,  847, ...,    0,    0,    0]])

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=40, test_size = 0.3, stratify=y)

In [51]:
X_train = np.asarray(X_train)
X_test = np.asarray(X_test)
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)

In [84]:
vec_size = 300
model = Sequential()
model.add(Embedding(vocab, vec_size, input_length=max_kata))
model.add(Conv1D(64,8,activation="relu"))
model.add(MaxPooling1D(1))
model.add(Dropout(0.5))

model.add(Dense(32, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(16, activation="relu"))
model.add(GlobalMaxPooling1D())
model.add(Dense(2, activation='softmax'))
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_9 (Embedding)      (None, 100, 300)          2354400   
_________________________________________________________________
conv1d_9 (Conv1D)            (None, 93, 64)            153664    
_________________________________________________________________
max_pooling1d_8 (MaxPooling1 (None, 93, 64)            0         
_________________________________________________________________
dropout_16 (Dropout)         (None, 93, 64)            0         
_________________________________________________________________
dense_24 (Dense)             (None, 93, 32)            2080      
_________________________________________________________________
dropout_17 (Dropout)         (None, 93, 32)            0         
_________________________________________________________________
dense_25 (Dense)             (None, 93, 16)          

In [85]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [86]:
model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
50/50 [==============================] - 7s 103ms/step - loss: 0.6990 - accuracy: 0.5079 - val_loss: 0.6891 - val_accuracy: 0.5007
Epoch 2/100
50/50 [==============================] - 5s 92ms/step - loss: 0.6194 - accuracy: 0.7234 - val_loss: 0.4568 - val_accuracy: 0.8517
Epoch 3/100
50/50 [==============================] - 5s 97ms/step - loss: 0.2056 - accuracy: 0.9319 - val_loss: 0.1637 - val_accuracy: 0.9559
Epoch 4/100
50/50 [==============================] - 5s 92ms/step - loss: 0.0328 - accuracy: 0.9912 - val_loss: 0.1285 - val_accuracy: 0.9545
Epoch 5/100
50/50 [==============================] - 15s 312ms/step - loss: 0.0119 - accuracy: 0.9975 - val_loss: 0.1298 - val_accuracy: 0.9545
Epoch 6/100
50/50 [==============================] - 17s 329ms/step - loss: 0.0055 - accuracy: 0.9994 - val_loss: 0.1309 - val_accuracy: 0.9545
Epoch 7/100
50/50 [==============================] - 7s 132ms/step - loss: 0.0038 - accuracy: 1.0000 - val_loss: 0.1340 - val_accuracy: 0.9515


Epoch 57/100
50/50 [==============================] - 5s 102ms/step - loss: 2.9125e-05 - accuracy: 1.0000 - val_loss: 0.3355 - val_accuracy: 0.9413
Epoch 58/100
50/50 [==============================] - 5s 98ms/step - loss: 2.8419e-04 - accuracy: 1.0000 - val_loss: 0.4520 - val_accuracy: 0.9339
Epoch 59/100
50/50 [==============================] - 5s 96ms/step - loss: 0.0019 - accuracy: 0.9994 - val_loss: 0.3647 - val_accuracy: 0.9325
Epoch 60/100
50/50 [==============================] - 5s 93ms/step - loss: 2.0996e-05 - accuracy: 1.0000 - val_loss: 0.3700 - val_accuracy: 0.9354
Epoch 61/100
50/50 [==============================] - 5s 93ms/step - loss: 2.5487e-04 - accuracy: 1.0000 - val_loss: 0.3775 - val_accuracy: 0.9383
Epoch 62/100
50/50 [==============================] - 5s 92ms/step - loss: 9.2592e-05 - accuracy: 1.0000 - val_loss: 0.3586 - val_accuracy: 0.9383
Epoch 63/100
50/50 [==============================] - 5s 91ms/step - loss: 1.4140e-05 - accuracy: 1.0000 - val_loss: 0.35

In [87]:
def get_encode(x):
    x = token.texts_to_sequences(x)
    x = pad_sequences(x, maxlen = max_kata, padding="post")
    return x

In [90]:
x = ['saya benci kamu']
x = get_encode(x)

In [91]:
model.predict_classes(x)

array([0], dtype=int64)